import SettingsLayout from "./SettingsLayout";


export default function About() {
    return <SettingsLayout title="About" explain="Learn more about Chatty-Web.">
        <h2 className="text-2xl font-bold">About Chatty Web</h2>
        <p>Chatty Web is a web client for NodeChatty, built with React and Vite. It provides a modern and responsive interface for accessing the features of NodeChatty on the web.</p>
        <p>Version: 1.0.0</p>
        <p>Built with React + Vite</p>
        <p className="italic opacity-15">hell, all these explaining texts are generated by autocomplete of VSCode Copilot XD</p>
    </SettingsLayout>;
}