import User from './User';
import PrivacySetting from './PrivacySetting';
import FriendRequest from './FriendRequest';
import Block from './Block';
import Message from './Message';
import File from './File';
import Conversation from './Conversation';
import Contact from './Contact';
User.hasOne(PrivacySetting, { foreignKey: 'user_id', as: 'privacy' });
PrivacySetting.belongsTo(User, { foreignKey: 'user_id' });
User.hasMany(FriendRequest, { foreignKey: 'from_user_id', as: 'sentRequests' });
User.hasMany(FriendRequest, { foreignKey: 'to_user_id', as: 'receivedRequests' });
FriendRequest.belongsTo(User, { foreignKey: 'from_user_id', as: 'fromUser' });
FriendRequest.belongsTo(User, { foreignKey: 'to_user_id', as: 'toUser' });
User.hasMany(Contact, { foreignKey: 'user_id', as: 'contacts' });
Contact.belongsTo(User, { foreignKey: 'friend_id', as: 'friend' });
User.hasMany(Block, { foreignKey: 'user_id', as: 'blocks' });
Block.belongsTo(User, { foreignKey: 'blocked_user_id', as: 'blockedUser' });
Message.belongsTo(User, { foreignKey: 'sender_id', as: 'sender' });
Message.belongsTo(User, { foreignKey: 'receiver_id', as: 'receiver' });
File.belongsTo(User, { foreignKey: 'uploader_id', as: 'uploader' });
Conversation.belongsTo(User, { foreignKey: 'peer_id', as: 'peer' });
Conversation.belongsTo(Message, { foreignKey: 'last_message_id', as: 'lastMessage' });
export { User, PrivacySetting, FriendRequest, Contact, Block, Message, File, Conversation, };
